config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '/user_account', to: 'users#show'
  resources :categories do 
    resources :transacts, only: [:new, :create]
  end
  resources :transacts, only: [:show]
  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :transacts

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/transact.rb
class Transact < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :categories

  validates :name, presence: true
  validates :amount, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  has_many :categories
  has_many :transacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:name, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @categories = current_user.categories
  end

  def show
    @category = Category.find_by(id: params[:id])
    @transacts = @category.transacts
  end

  def new
    @new_category = Category.new
  end

  def create
    category = Category.new(user: current_user)
    category.assign_attributes(categories_params)
    if category.save
      redirect_to categories_path
      flash[:success] = 'The category was created!'
    else
      flash.now[:error] = 'Could not create category, try again'
      render :new, status: :unprocessable_entity
    end
  end

  private

  def categories_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/transacts_controller.rb
class TransactsController < ApplicationController
  before_action :authenticate_user!

  def show
    @transact = Transact.find_by(id: params[:id])
  end

  def new
    @new_transact = Transact.new
    @categories = current_user.categories
  end

  def create
    @category = Category.find_by(id: params[:category_id])
    transact = Transact.new(user: current_user)
    transact.assign_attributes(transacts_params)
    categories_id.each do |id|
      transact.categories << Category.find_by(id:)
    end

    if transact.save
      flash[:success] = 'The category was created!'
      redirect_to @category
    else
      flash.now[:error] = 'Could not create category, try again'
      render :new, status: :unprocessable_entity
    end
  end

  private

  def transacts_params
    params.require(:transact).permit(:name, :amount)
  end

  def categories_id
    params.require(:transact).permit(category_ids: [])[:category_ids]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    return unless current_user

    redirect_to categories_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def navbar_helper(path)
    if path.include?('transacts')
      'shared/back'
    elsif path.include?('categories/')
      'shared/back_home'
    else
      'shared/toggle'
    end
  end

  def wallpaper
    if ['/', '/users/sign_in', '/users/sign_up'].include? request.fullpath
      'splash-page'
    else
      ''
    end
  end
end

app/views/categories/_category.html.erb
<div class="card mx-auto my-2 category col-lg-3 mx-lg-3">
  <%= link_to category_path(category), class: "custom-link" do %>
    <div class="card-body row">
      <div class="col-4">
        <img src="<%= category.icon%>" alt="<%= category.icon%>", class="img-fluid">
      </div>
      <div class="text-center my-2 col-8">
        <h5 class="card-title"><%= category.name%> </h5>
        <p class="card-text">Transactions: <%= category.transacts.count%> </p>
      </div>
    </div>
  <% end %>
</div>

app/views/categories/_transact.html.erb
<div class="card mx-auto my-3 my-lg-2 col-lg-5 mx-lg-2">
  <%= link_to transact_path(transact), class: "custom-link" do %>
    <div class="card-body row">
      <h5 class="card-title col-8"><%= transact.name %> </h5>
      <div class="text-center my-2 col-4">
        <p class="card-text"><%= number_to_currency(transact.amount)%> </p>
      </div>
      <span class="col-4 small"><%= transact.created_at.to_date %></span>
    </div>
  <% end %>
</div>

app/views/categories/index.html.erb
<div class="row justify-content-lg-center px-2 category-container">
  <% @categories.each do |category|%>
    <%= render 'category', category: category %>
  <%end%>
</div>
<div class="add-button-container mt-5 my-lg-5">
  <%= link_to 'Add new category', new_category_path, class:"custom-link add-button" %>
</div>

app/views/categories/new.html.erb
<div class='my-5 pt-5'>
  <h2 class='text-center'>Create new category</h2>
  <%= form_with model: @new_category, url: categories_path, method: :post, local: true, scope: :category do |f| %>
    <div class="row g-3">
      <div class="col-md-5 mb-3">
        <%= f.label :name, class: "form-label" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="col-md-6 mb-3">
        <%= f.label :icon, class: "form-label" %>
        <%= f.text_field :icon, class: "form-control", placeholder: 'URL'  %>
      </div>
      <div class="text-center">
        <%= f.submit 'Create category', class:"button button-green" %>
      </div>
    </div>
  <% end %>
</div>

app/views/categories/show.html.erb
<div class="text-center">
  <h3><%= @category.name%></h3>
  <h5 class="text-center">Total = <%= number_to_currency(@transacts.sum(:amount)) %> </h5>
</div>
<div class="row justify-content-lg-center px-2 category-container">
  <% @transacts.each do |transact| %>
    <%= render 'transact', transact: transact%>
  <%end%>
</div>
<div class="add-button-container py-lg-4">
  <%= link_to 'Add a transaction', new_category_transact_path(@category), class: 'add-button custom-link' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </head>
  <body class=<%= wallpaper %>>
    <%= render 'shared/navbar'%>
    <div class="container pt-lg-5 pt-4 mt-5">
    <%= yield %>
  </div>
</body>
</html>

app/views/shared/_back.html.erb
<%= link_to '', :back, class: 'custom-link bi bi-arrow-left text-light' %>

app/views/shared/_back_home.html.erb
<%= link_to '', '/categories', class: 'custom-link bi bi-arrow-left text-light' %>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <nav class="navbar fixed-top">
    <div class="container-fluid">
      <%= render partial: navbar_helper(request.path) %>
      <a class="navbar-brand text-light" href="/">Budget App</a>
      <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Budget App</h5>
          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
            <li class="nav-item">
              <i class="bi bi-list text-light"></i>
              <a class="nav-link" href="/categories">Categories</a>
            </li>
            <li class="nav-item">
              <i class="bi bi-plus-square-fill text-light"></i>
              <a class="nav-link" href="/categories/new">Add Category</a>
            </li>
            <li class="nav-item">
              <i class="bi bi-person-circle text-light"></i>
              <a class="nav-link" href="/user_account">Account </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </nav>
<%end%>

app/views/shared/_toggle.html.erb
<button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
  <%= image_tag "toggle.png", class: 'navtoggler' %>
</button>

app/views/transacts/new.html.erb
<div class='my-5 pt-5'>
  <h2 class='text-center'>Create new transaction</h2>
  <%= form_with model: @new_transact, url: category_transacts_path, method: :post, local: true, scope: :transact do |f| %>
    <div class="row g-3">
      <div class="col-md-6 mb-3">
        <%= f.label :name, class: "form-label" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="col-md-2 mb-3">
        <%= f.label :amount, class: "form-label" %>
        <%= f.number_field :amount, value: number_to_currency(f.object.amount.to_f, delimiter: '', unit: ''), step: :any, class: "form-control" %>
      </div>
      <label for="category">Add to a category</label>
      <% @categories.each do |category| %>
        <div class="form-check">
          <%= f.check_box :category_ids, { multiple: true }, category.id, nil %>
          <%= label_tag "transaction_category_#{category.id}", category.name %>
        </div>
      <% end %>
      <div class="text-center">
        <%= f.submit 'Post transaction', class:"button button-green mb-3" %>
      </div>
    <% end %>
  </div>

app/views/transacts/show.html.erb
<div class="card mx-auto my-3">
  <div class="card-body row">
    <h5 class="card-title col-8"><%= @transact.name%></h5>
    <div class="my-2 col-4">
      <p class="card-text"><%= number_to_currency(@transact.amount)%> </p>
    </div>
    <p class="small mt-auto">Categories: 
      <% categories_array = @transact.categories.map {|category| category.name}%>
      <%= categories_array.join(', ') %>
    </p>
  </div>
</div>

app/views/users/index.html.erb
<div class="pt-5 ">
  <h2 class="text-center text-light">Bugget App</h2>
  <p class="text-center px-5 my-5 fs-4 text-light">You're not logged in, please log into your account or sign in.</p>
  <div class="row g-3 mt-4">
    <div class="col-md-10 mt-4 text-center text-lg-end col-lg-6">
      <%= link_to "Sign in", new_user_session_path, class:'button button-blue custom-link text-light splash sign-in' %>
    </div>
    <div class="col-md-10 mt-4 text-center text-lg-start col-lg-6">
      <%= link_to "Sign up", new_user_registration_path, class:'button button-blue custom-link text-light splash'%>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="pt-5">
  <% if user_signed_in? %>
    <div class="display-6"> Welcome <%= current_user.email %>! </div>
    <div class="row g-3 mt-4">
      <div class="col-md-4 mt-4">
        <%= button_to "Sign out", destroy_user_session_path, method: :delete, class:'btn btn-danger' %>
      </div>
      <div class="col-md-4 mt-4">
        <%= link_to "Update account info", edit_user_registration_path, class:'btn btn-secondary' %>
      </div>
    </div>
  <% else %>
    <div class="h2 text-center">You're not logged in, please log into your account or sign in.</div>
    <div class="my-5 text-center">
      <%= button_to "Sign in", new_user_session_path, class:'btn btn-primary' %>
    </div>
  <% end %>
</div>